### ISSUE TITLE
Is castling working?

### ISSUE THREAD

**Issue by licaon-kter** [MatthewDorner/mattermost-plugin-chess#10]
I can't seem to be able to trigger it.

Ref: https://github.com/jhlywa/chess.js/issues/219

**Comment by MatthewDorner** [comment]
It was working back when I tested it last, can you provide a screenshot of a specific game state where if you attempt to castle, it won't work?

**Comment by licaon-kter** [comment]
Don't have one now, will make a mockup.

**Comment by Roy-Orbison** [comment]
Works for me in current version.

**Comment by MatthewDorner** [comment]
Unable to reproduce, users report castling is working in current version. Closing issue.
