### ISSUE TITLE
Channel name incomplete

### ISSUE THREAD

**Issue by licaon-kter** [MatthewDorner/mattermost-plugin-chess#11]
Starting a game with a random bot, eg. Remindbot channel name is `Chess: Remindbot VS MyNick`

But against a real user it's just `Chess: VS MyNick` or `Chess: MyNick VS`

Mattermost 5.29.1

**Comment by MatthewDorner** [comment]
I'm looking into this, sorry I haven't been active much.

**Comment by MatthewDorner** [comment]
I'm guessing it's that the user you're challenging doesn't have a first name set?

The channel name is based on the user's first name, not nickname or username, so I can try to improve that in a next release. Probably just use username instead.
