### ISSUE TITLE
Game board does not keep up (but move list does)

### ISSUE THREAD

**Issue by Roy-Orbison** [MatthewDorner/mattermost-plugin-chess#25]
If I leave the board dialogue open, and my opponent moves, their move appears in the list to the left and becomes highlighted as the latest move. However, the board does not change from my last move. I have to press `>` to obtain the new position.

**Comment by MatthewDorner** [comment]
Thanks for the heads up. Guess I forgot to test that after switching to the new chessboard library 🙃

**Comment by MatthewDorner** [comment]
Released fixed version: https://github.com/MatthewDorner/mattermost-plugin-chess/releases/tag/v1.2.1

**Comment by Roy-Orbison** [comment]
Works for me, cheers!
