### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ghost** [MatthewDorner/mattermost-plugin-chess#3]
Hey Guys,

sorry for that very basic question but how do i intsall it? I tried to downloaod it and copied the extracted files to the plugin directory but it didnt work :(

Server is: 5.21.0

LG 
Frankie

**Comment by manuelsanjosebelda** [comment]
Hi Frankie-D-RDVLT,

In my case, In the control pannel of the mattermost (web), in Plugin Marketplace section, there is a other section named 'installed', automatically, all the plugins you have in the server 'plugin' folder will be detected.

I hope I have helped =)

**Comment by MatthewDorner** [comment]
I just updated `README.md` with installation instructions. Let me know if you have any other issues.
